---
name: Build and Deploy Cyberfolio Server
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'

      - name: Install Yarn v1
        run: npm install -g yarn@1.22.22

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/ # Adjust based on your output dir

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build # Waits for build to finish

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > .env
          echo "MORALIS_API_URL=${{ secrets.MORALIS_API_URL }}" >> .env
          echo "MORALIS_API_KEY=${{ secrets.MORALIS_API_KEY }}" >> .env

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/*'
          target: '/home/root/projects/cyberfolio-server/dist'

      - name: SSH into server and restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/projects/cyberfolio-server
            pm2 restart cyberfolio-server || pm2 start dist/index.js --name cyberfolio-server
