---
name: Build and Deploy Cyberfolio Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.1.0'

      - name: Install Yarn v1
        run: npm install -g yarn@1.22.22

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/ # Adjust based on your output dir

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build # Waits for build to finish

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Create .env file
        run: |
          echo "NODE_ENV=production" > dist/.env
          echo "PORT=${{ secrets.PORT }}" >> dist/.env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> dist/.env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> dist/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> dist/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> dist/.env
          echo "JWT_EXPIRY_IN_DAYS=${{ secrets.JWT_EXPIRY_IN_DAYS }}" >> dist/.env
          echo "INFURA_API_URL=${{ secrets.INFURA_API_URL }}" >> dist/.env
          echo "INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}" >> dist/.env
          echo "COINGECKO_V3_API_URL=${{ secrets.COINGECKO_V3_API_URL }}" >> dist/.env
          echo "COINMARKETCAP_API_KEY=${{ secrets.COINMARKETCAP_API_KEY }}" >> dist/.env
          echo "COINMARKETCAP_API_URL=${{ secrets.COINMARKETCAP_API_URL }}" >> dist/.env
          echo "COVALENT_V1_API_URL=${{ secrets.COVALENT_V1_API_URL }}" >> dist/.env
          echo "COVALENT_API_KEY=${{ secrets.COVALENT_API_KEY }}" >> dist/.env
          echo "MORALIS_API_URL=${{ secrets.MORALIS_API_URL }}" >> dist/.env
          echo "MORALIS_API_KEY=${{ secrets.MORALIS_API_KEY }}" >> dist/.env
          echo "BLOCKCHAIN_INFO_API_URL=${{ secrets.BLOCKCHAIN_INFO_API_URL }}" >> dist/.env
          echo "BINANCE_API_URL=${{ secrets.BINANCE_API_URL }}" >> dist/.env
          echo "BINANCETR_API_URL=${{ secrets.BINANCETR_API_URL }}" >> dist/.env
          echo "KUCOIN_API_URL=${{ secrets.KUCOIN_API_URL }}" >> dist/.env
          echo "KUCOIN_API_VERSION=${{ secrets.KUCOIN_API_VERSION }}" >> dist/.env
          echo "KUCOIN_API_VERSION=${{ secrets.KUCOIN_API_VERSION }}" >> dist/.env

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/*
          target: '/home/root/projects/cyberfolio-server'

      - name: SSH into server and restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/projects/cyberfolio-server
            pm2 delete cyberfolio-server 
            pm2 start dist/index.js --name cyberfolio-server
